"""Create application and app stage

Revision ID: f6b03abd03c8
Revises: a41ac5be4596
Create Date: 2024-12-19 22:02:34.850684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b03abd03c8'
down_revision: Union[str, None] = 'a41ac5be4596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROSPECT', 'APPLIED', 'INTERVIEWING', 'OFFERED', 'ACCEPTED', 'REJECTED', name='applicationstatusenum'), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('date_first_response', sa.DateTime(), nullable=True),
    sa.Column('date_rejected', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('application_stages',
    sa.Column('application_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'REJECTED', 'PENDING', name='applicationstagestatus'), nullable=True),
    sa.Column('date_scheduled', sa.DateTime(), nullable=True),
    sa.Column('date_occurred', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['applications.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_stages')
    op.drop_table('applications')
    # ### end Alembic commands ###
