"""Create Application Table

Revision ID: 98902eb76296
Revises: 
Create Date: 2024-10-25 14:48:12.115167

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98902eb76296"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applications")
    # ### end Alembic commands ###
